# Generated by Django 4.2.2 on 2023-06-27 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
